### ISSUE TITLE
QuML Editor feature to upload audio

### ISSUE THREAD

**Issue by sajeshkayyath** [Sunbird-inQuiry/editor#40]
**Project Details**
---
**What is Sunbird inQuiry?**

Sunbird inQuiry is a software building block that enables setting up of question banks for various use cases such as assessments, quizzes, practice worksheets, surveys, and many more. These are applicable in multiple domains related to education and human development. 

Here are some examples of solutions that can be enabled through Sunbird inQuiry:

- Conduct assessments which can evaluate users’ understanding of concepts and issue certificates based on assessment score. 
- Evaluate assessment data to take informed decisions and plan for interventions. 
- Launch surveys to collect feedback and analyse responses. 

**Question Set Editor (QuML editor)**

Question set editor is a tool offered by inQuiry to help you kickstart your creation of Question Banks. 

More details are [here](https://inquiry.sunbird.org/learn/readme)

**Features to be implemented**
---
**QuML Editor feature to upload audio**

QuML editor currently offers options to upload images and video based solutions. This needs to be extended further to enable uploading of audio based solutions. 

**What exists**

- QuML Editor that offers uploading of image and video based solutions [here](https://github.com/Sunbird-inQuiry/editor/tree/release-5.6.0)
- QuML player that is capable of playing image, audio and video based solutions.
- QuML [Specification](https://quml.sunbird.org/)
- Backend APIs that is needed for the application to function

**What needs to be build**
 
- [ ] Enhance QuML editor to upload audio based solutions.
- [ ] Test it with the existing player to play the audio based solutions

**Learning Path**
---

**Complexity**
Medium

**Skills Required**
Angular

**Name of Mentors**
@vaibhavbhuva  

**Project size**
3 Weeks

**Product Set Up**
---
Instruction to install the application is available [here](https://github.com/Sunbird-inQuiry/editor/tree/release-5.6.0)

**Acceptance Criteria**
---
- [ ] QuML Editor is able to upload audio based solutions
- [ ] QuML Editor functionality of uploading video and image should continue to function
- [ ] Audio based solutions are playable in the QuML player
- [ ] Video and Image based solutions continue to function in QuML player

**Out of Scope**
---
Enhancing QuML player

**Milestones**
---
- [ ] Understanding the requirements
- [ ] Understanding QuML Editor
- [ ] Understanding QuML Specification
- [ ] Setting up the QuMl Editor
- [ ] Changes to the QuML editor to support audio upload
- [ ] Testing the application to cover the use cases

**Comment by KOWSHIQKATTAMURI** [comment]
Hello Sunbird inQuiry,

I hope this message finds you well. My name is Kowshiq Kattamuri, and I am an upcoming fourth-year student at NIT Calicut. I have experience working with the MERN stack and have developed an e-commerce website in the past. I am excited about the opportunity to contribute to the Sunbird inQuiry project and believe that my skills in Angular will be valuable in implementing the desired features.

I am particularly interested in working on enhancing QuML editor to upload audio-based solutions. I have a few ideas on how to approach the given task.

I'm excited to contribute to this project and aid in expanding the capabilities of the QuML Player. My experience in web development and my love of making user-friendly interfaces will be a benefit to the team, in my opinion. I'm eager to expand on my ideas and discover how I can most effectively help the project succeed.

**Comment by alpit4** [comment]
Hello Please assign this issue to me, so that I can add up the feature of input audio signal which will be fast and very useful for the users.

**Comment by vaibhavbhuva** [comment]
Hi All, Thanks for your interest in our project. 
Please do setup the application locally and the required changes to upload audio. 
Kindly prepare the proposal and submit it in unstop platform and join discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for continuous updates.

Instruction to install the application is available [here](https://github.com/Sunbird-inQuiry/editor/tree/release-5.6.0)

**Comment by PrathameshGujar08** [comment]
Hello @vaibhavbhuva I need some help setting it up and ig I will be done with the proposal for it. Would require your help in it if you could

**Comment by vaibhavbhuva** [comment]
Hi All,
We are conducting a 30-minute Q&A and issue clarification session to address any doubts regarding proposal submission or any other concerns to clarify.

Here are the session details for the connect:
--------------------------------------------
Date: 9th June 2023 - Friday (Today)
Time: 05:30 PM to 06:00 PM
Meeting Link: [https://teams.microsoft.com/l/meetup-join/](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjJkYjJkZmYtNjE4Yy00NDJiLTk2NTItNDcyYzI0ZWRhMzUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d2f80462-bf28-4055-8ef3-085d8e4b2ed0%22%2c%22Oid%22%3a%22323d9efe-7829-46ea-85a5-a33d85aa206a%22%7d)

Kindly join discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for continuous updates.
Looking forward to meeting you all.

Thank you.
