### ISSUE TITLE
A tool that auto generates questions in QuML format

### ISSUE THREAD

**Issue by sajeshkayyath** [Sunbird-inQuiry/editor#41]
**Project Details**
---
**What is Sunbird inQuiry?**

Sunbird inQuiry is a software building block that enables setting up of question banks for various use cases such as assessments, quizzes, practice worksheets, surveys, and many more. These are applicable in multiple domains related to education and human development. 

Here are some examples of solutions that can be enabled through Sunbird inQuiry:

- Conduct assessments which can evaluate users’ understanding of concepts and issue certificates based on assessment score. 
- Evaluate assessment data to take informed decisions and plan for interventions. 
- Launch surveys to collect feedback and analyse responses. 

**Question Set Editor (QuML editor)**

Question set editor is a tool offered by inQuiry to help you kickstart your creation of Question Banks. 

More details are [here](https://inquiry.sunbird.org/learn/readme)

**Features to be implemented**
---
**A tool that auto generates questions in QuML format by taking a story/chapter as an input - using AI**

The questions are currently prepared manually and injected using the QuML editor. As part of this requirement, a standalone tool has to be build that can take in a story/chapter as input and auto generate questions in QuML format. Questions that are auto generated will be of type multi choice and subjective.

**What exists**

- QuML [Specification](https://quml.sunbird.org/)
- QuML player that is capable of playing multi choice and subjective questions.

**What needs to be build**
 
- [ ] A standalone AI tool that can take in a story/chapter as input and auto generate questions in QuML format
- [ ] Schema validation to ensure the generated question complies to QuML format.
- [ ] Questions that are auto generated are of type multi choice and subjective questions

**Learning Path**
---

**Complexity**
Medium

**Skills Required**
Open source AI tooling
JSON Schema

**Name of Mentors**
@krgauraw   

**Project size**
?? Weeks - TBD

**Product Set Up**
---
Details of the QuML specification is available [here](https://quml.sunbird.org/). The software stack that is needed for the standalone application is to be setup newly.

**Acceptance Criteria**
---
- [ ] New tool is able to take input as story/chapter and auto generate questions 
- [ ] Questions generated are complying to QuML Specification
- [ ] Change suggestion to QuML Specification if any
- [ ] Open source software to be used
- [ ] No vendor lock in

**Out of Scope**
---
Enhancing existing QuML player and QuML Editor
Implementing additional question types apart from multi choice and subjective

**Milestones**
---
- [ ] Understanding the requirements
- [ ] Understanding QuML Specification
- [ ] Submit the solution for the new tool
- [ ] Solution approval
- [ ] Setting up the app
- [ ] Generating questions from any given story/chapter
- [ ] Generating question complying to QuML specification
- [ ] Validating the questions against the QuML specification
- [ ] Testing the application to verify different question types
- [ ] Solution proposal for auto generating questions for new types like Fill in the blanks and match the following.

**Comment by prakharrathi25** [comment]
Hi, would we be building our own AI solutions in this or will it require pre-existing LLM capabilities. I have worked on both in the past and would love to work on this project!

**Comment by prashant2-4-4** [comment]
Hi , I would want to work on this. from resource point of view If resources are limited, building your own AI system may be a viable option. Open-source LLMs like Llama 7B require significant GPU resources (14GB+) for inference. However, if sufficient resources are available, utilizing pre-trained LLMs can be beneficial since they are trained on extensive datasets.

**Comment by goyalpramod** [comment]
Heya there @sajeshkayyath my understanding of the problem is there is an AI tool already created by sunbird inquiry that will be accessible to us. 
We have to generate a user interface that can take in text input that is in the form of a story or such and generate questions based on that in a particular format. Kindly let me know if my understanding is correct so I can further work on it.

**Comment by goyalpramod** [comment]
Heya there @sajeshkayyath my understanding of the product and the project is. Inquiry provides a platform in which you can input images in the question markup language. And it generates questions for you. 

I have but three questions. 

In the overview video it has been mentioned that  inquiry is capable of authorising and publishing. Using an external API. 

1. What is the input that is being provided to this API? 

2. Do we have access to this API? 

3. The AI tool that we are to develop. What is expected of us? Because we certainly do not have the resources (as an individual) to train an LLM 

My further understanding is, after developing the AI tool. We need to develop an interface that can take in a story and develop the questions in QuML format. 

(Kindly let me know if i got anything wrong)

**Comment by vaibhavbhuva** [comment]
Hi All,
We are conducting a 30-minute Q&A and issue clarification session to address any doubts regarding proposal submission or any other concerns to clarify.

Here are the session details for the connect:
--------------------------------------------
Date: 9th June 2023 - Friday (Today)
Time: 05:30 PM to 06:00 PM
Meeting Link: [https://teams.microsoft.com/l/meetup-join/](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjJkYjJkZmYtNjE4Yy00NDJiLTk2NTItNDcyYzI0ZWRhMzUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d2f80462-bf28-4055-8ef3-085d8e4b2ed0%22%2c%22Oid%22%3a%22323d9efe-7829-46ea-85a5-a33d85aa206a%22%7d)

Kindly join discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for continuous updates.
Looking forward to meeting you all.

Thank you.

**Comment by krgauraw** [comment]
Hi @prakharrathi25 / @prashant2-4-4 / @goyalpramod Are you guys writing proposals? If yes, please submit it on unstop platform.

**Comment by goyalpramod** [comment]
@krgauraw heya there, I have submitted a proposal in unstop. Kindly let me know if it's not visible. Because it shows submitted from my side.

**Comment by prashant2-4-4** [comment]
Yes, I am writing and I will submit it by today.
