### ISSUE TITLE
Player/Editor to support new type of questions

### ISSUE THREAD

**Issue by sajeshkayyath** [Sunbird-inQuiry/editor#42]
**Project Details**
---
**What is Sunbird inQuiry?**

Sunbird inQuiry is a software building block that enables setting up of question banks for various use cases such as assessments, quizzes, practice worksheets, surveys, and many more. These are applicable in multiple domains related to education and human development. 

Here are some examples of solutions that can be enabled through Sunbird inQuiry:

- Conduct assessments which can evaluate users’ understanding of concepts and issue certificates based on assessment score. 
- Evaluate assessment data to take informed decisions and plan for interventions. 
- Launch surveys to collect feedback and analyse responses. 

**Question Set Editor (QuML editor)**

Question set editor is a tool offered by inQuiry to help you kickstart your creation of Question Banks. 

**Question Set Player (QuML player)**

Question set player is a player provided by inQuiry to create engaging & inclusive experiences for end users consuming the question sets.

More details are [here](https://inquiry.sunbird.org/learn/readme)

**Features to be implemented**
---
**Implementing new question type of match the following**

Currently the QuML editor and player supports only multi choice question and subjective question. As part of this requirement, we need to introduce the match the following question type.

**What exists**

- QuML [Specification](https://quml.sunbird.org/)
- [QuML Player](https://github.com/Sunbird-inQuiry/player/tree/release-5.6.0) that is capable of playing multi choice and subjective questions.
- [QuML Editor](https://github.com/Sunbird-inQuiry/editor/tree/release-5.6.0) that is capable of creating multi choice and subjective questions.

**What needs to be build**
 
- [ ] Enhance the QuML Editor to create match the following question.
- [ ] Enhance the QuML Player to play match the following question.
- [ ] Adherence to the QuML specification

**Learning Path**
---

**Complexity**
Medium

**Skills Required**
Angular and Node

**Name of Mentors**
@krgauraw / @vaibhavbhuva / @rajnishdargan 

**Project size**
?? Weeks - TBD

**Product Set Up**
---
Details of the QuML specification is available [here](https://quml.sunbird.org/). 
Instruction to install the QuML editor is available [here](https://github.com/Sunbird-inQuiry/editor/tree/release-5.6.0)
Instruction to install the QuML Player is available [here](https://github.com/Sunbird-inQuiry/player/tree/release-5.6.0)

**Acceptance Criteria**
---
- [ ] New match the following question can be created using the QuML Editor 
- [ ] Questions generated are complying to QuML Specification
- [ ] New match the following question can be played using the QuML Player

**Out of Scope**
---
Enhancing the Backend API

**Milestones**
---
- [ ] Understanding the requirements
- [ ] Understanding QuML Specification
- [ ] Understanding QuML Editor
- [ ] Understanding QuML Player
- [ ] Submit the solution for incorporating the match the following question
- [ ] Solution approval
- [ ] Setting up the QuML Editor
- [ ] Setting up the QuML Player
- [ ] Developing the solution for the new question type in QuML editor
- [ ] Developing the solution for the new question type in QuML player
- [ ] Testing the question creation flow in QuML Editor
- [ ] Testing the question playable flow in QuML Player
- [ ] Testing the new question type along with ensuring the existing question types has no issues

**Comment by PrathameshGujar08** [comment]
Hello Mentors! I would like to work on this. Can you help me get started and are any issues open?

**Comment by kavania2002** [comment]
Hello Mentors!
I have been looking into the documents of QuML Editor and Player and also looked into the architecture of InQuiry.
Now I'll set up the Editor and Player, anything else I must do that might help with this issue?

**Comment by rajnishdargan** [comment]
Hi @PrathameshGujar08 @kavania2002 @vinayastar01 
Thanks for your interest in our project. Please do setup application in local, also make sure to prepare and submit your proposal in unstop platform and join in discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for any communication.
Here is the setup steps for [player](https://inquiry.sunbird.org/use/developer-installation/question-set-player/installation#:~:text=QuML%20Player%20Contribution%20Guide) and [editor](https://inquiry.sunbird.org/use/developer-installation/question-set-editor/installation#:~:text=Questionset%20Editor%20Contribution%20Guide)

**Comment by vaibhavbhuva** [comment]
Hi All,
We are conducting a 30-minute Q&A and issue clarification session to address any doubts regarding proposal submission or any other concerns to clarify.

Here are the session details for the connect:
Date: 9th June 2023 - Friday (Today)
Time: 05:30 PM to 06:00 PM
Meeting Link: [https://teams.microsoft.com/l/meetup-join/](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjJkYjJkZmYtNjE4Yy00NDJiLTk2NTItNDcyYzI0ZWRhMzUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d2f80462-bf28-4055-8ef3-085d8e4b2ed0%22%2c%22Oid%22%3a%22323d9efe-7829-46ea-85a5-a33d85aa206a%22%7d)

Kindly join discord [channel](https://discord.com/channels/973851473131761674/1106637310042329159) for continuous updates.
Looking forward to meeting you all.

Thank you.
